GET http://localhost:3001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTI5OTYxNjIsImV4cCI6MTU5Mjk5NjE3NywiYXVkIjoiNWVlYTBlOTlkMTU3ZjYzZjNlMzYxYjQxIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.fsED23a_2dINM1saPjmHkc_gVrsuptb1oSNh0GR-03M

###Login Route
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "jhond9@gmail.com",
  "password": "1234"
}


###Register Route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "kotariSudeep@gmail.com",
  "password": "1234"
}

###Refresh token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTI5OTYxMzcsImV4cCI6MTYyNDU1MzczNywiYXVkIjoiNWVlYTBlOTlkMTU3ZjYzZjNlMzYxYjQxIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.9kFX7LEzyh6eopqF_TGZQRwYqrIPUUdN441ekfKxu7Q"
}

###Logout Route
DELETE http://localhost:3001/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTg2NDA0NTksImV4cCI6MTY1MDE5ODA1OSwiYXVkIjoiNjA3YTc3Y2RlNDFmYTEwYmU1ZTY4ZWE4IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.5-kiPGk3LdFVkqXTzOuU_wbPiKaf7jBUune4v4H12yI"
}