GET http://localhost:3001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAwMDk4NDMsImV4cCI6MTYyMDAwOTg3MywiYXVkIjoiNjA4ZjYyYWYzYWUxMmQxYTNjOTliYTFhIiwiaXNzIjoiY29sbGVnZXF1ZXJ5LmNvbSJ9.8jA0eR7y0lW6drSzFwM5TVDxyFCr_ts8TJrTchgBqXk

###Login Route
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "sudeepkotari@gmail.com",
  "password": "sudeepK@97"
}


###Register Route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "emailVerificationToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic3VkZWVwIiwiZW1haWwiOiJzdWRlZXBrb3RhcmlAZ21haWwuY29tIiwicGFzc3dvcmQiOiIxMjM0NTY3OSIsImlhdCI6MTYyMDAwOTUyOCwiZXhwIjoxNjIwMDEwNDI4LCJpc3MiOiJjb2xsZWdlcXVlcnkuY29tIn0.eepv5VDQwcyjMdbrhPuEQHZLT8fGasXehm4JJIczZLw"
}

###
POST http://localhost:3001/auth/verify-email
Content-Type: application/json

{
  "name":"kotari",
  "email": "bbhc412@bbhegdecollege.com",
  "password": "12345679",
  "about": " ",
  "profileUrl": " "
}

###Refresh token Route
POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAxMDcxNDAsImV4cCI6MTYyMDEwNzE3MCwiYXVkIjoiNjA5MGRkMTI0MzgxNzQxMjc0NzFkOGYwIiwiaXNzIjoiY29sbGVnZXF1ZXJ5LmNvbSJ9.lgvSPLYKjMSuzsE9Pc66DTRs7A5JqYDDmVrdtWVYTDQ"
}

###Logout Route
DELETE http://localhost:3001/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjEzOTQwNDgsImV4cCI6MTY1Mjk1MTY0OCwiYXVkIjoiNjA5NjNiNjlkY2U3OGEwMDIyYzEwZjgxIiwiaXNzIjoiY29sbGVnZXF1ZXJ5LmNvbSJ9.1C0t_v3ow0P0FJZvkNeOPsIzt5Lp0E5cLBuF3pDOPSQ"
}

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
###
https://college-query.web.app